server:
  port: 8080
spring:
  application:
    name: LaoYeGymnasium  #指定应用的名称，不配置则默认为工程名
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/gym?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 446652130
#  redis:
#    host: localhost
#    port: 6379
#    password:
#    database: 0
  #设置过期时间，不设置则默认为永久存在(单位为毫秒，则这里是1800秒，即30分钟）
#  cache:
#    redis:
#      time-to-live: 1800000 #其实这么设置容易导致缓存雪崩，不太好
  #  开启热部署，加快开发，开发完成后关闭热部署（记得添加依赖）
  devtools:
    restart:
      enabled: true

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
laoye:
  path: D:\ProgramGrocery\JavaProgram\projectpratice\LaoYeGymnasium\src\main\resources\img_file\